# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]

In [4]:
print("Data", "Science", "Mentorship", "Program", sep="-", end="-started-")
print("By", "CampusX", sep="-")

Data-Science-Mentorship-Program-started-By-CampusX

In [ ]:
# Write your code here
print("Data", "Science", "Mentorship", "Program",sep="-",end="-started-")
print("By", "CampusX",sep="-")

Data-Science-Mentorship-Program-started-By-CampusX

### Q2:- Write a program that will convert celsius value to fahrenheit.

In [5]:
c=float(input("Enter the temperature in celcius: "))
f= c*(9/5) + 32
print(f)

Enter the temperature in celcius: 1
33.8

In [ ]:
# Write your code here
celcius=float(input('Enter calcius value: '))
fahrenheit=celcius*9/5+32
print("in fahrenheit: ", fahrenheit, "F")

Enter calcius value: 1
in fahrenheit:  33.8 F

### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax.

In [ ]:
# Write your code here
a=int(input("Enter number 1: "))
b=int(input("Enter number 2: "))
print(a,b)

temp=a
a=b
b=temp

print(a,b)

Enter number 1: 2
Enter number 2: 6
2 6
6 2

In [ ]:
# Write your code here by special python syntax
a=int(input("Enter number 1: "))
b=int(input("Enter number 2: "))
print(a,b)

a,b=b,a             #this is a special python syntax i am using
print(a,b)

Enter number 1: 3
Enter number 2: 2
3 2
2 3

### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input.---------distance=square root of (x2-x1)^2 + (y2-y1)^2


> Add blockquote

In [ ]:
# Write your code here
p1x=int(input("Enter point 1's x coordinate: "))
p1y=int(input("Enter point 1's y coordinate: "))
p2x=int(input("Enter point 2's x coordinate: "))
p2y=int(input("Enter point 2's y coordinate: "))

euclidian_distance=((p2x-p1x)**2 + (p2y-p1y)**2)**0.5

print(round(euclidian_distance,2))   #round fn give a large no in round figure...here using 2 point round fig

Enter point 1's x coordinate: 3
Enter point 1's y coordinate: 5
Enter point 2's x coordinate: 6
Enter point 2's y coordinate: 8
4.24

### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

In [ ]:
# Write your code here
principle=int(input("Enter the principle value: "))
rate=int(input("Enter interest rate: "))
time=int(input("Enter time: "))

si=(principle*rate*time)/100

print("The interest is: ",si)

Enter the principle value: 10000
Enter interest rate: 5
Enter time: 2
The interest is:  1000.0

### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.----hint--let,H=4, L=10---C+D=4, 2C+4D=10 and solve

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2

In [ ]:
# Write your code here

### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.
hint*--we can directly use loop but use formula here, the sum of the squares of first n natural nos= n(n+1)(2n+1)/6

In [ ]:
# Write your code here
n=int(input("Enter the no. you want its first natural nos sum: "))
sum=n*(n+1)*(2*n+1)/6
print("Sum of squares of natural nos of your no.: ",sum)

Enter the no. you want its first natural nos sum: 3
Sum of squares of natural nos of your no.:  14.0

### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user.

*hint---an=a+(n-1)d

In [ ]:
# Write your code here
first_term=int(input("Enter first term: "))         #first=1
second_term=int(input("Enter second term: "))       #second=3
n=int(input("Enter the value of n: "))              #n=8

d=second_term-first_term                            #d=3-1=2

an=first_term+(n-1)*d         #1,3,5,7,9,11,13,15------15 is the 8th term in the sequence
print(an)                                           # Result= 15

Enter first term: 1
Enter second term: 3
Enter the value of n: 8
15

### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user.

hint---(2/3)+(4/5) we cross multiply then add or minus whatever operators are used jus used like equation and solve

In [ ]:
# Write your code here
n1=int(input("Enter first term numerator: "))
d1=int(input("Enter first term denominator: "))
n2=int(input("Enter second term numerator: "))
d2=int(input("Enter second term denominator: "))

result_n=n1*d2+d1*n2
result_d=d1*d2

#print("The sum of the two fractions are: ", result_n,"/",result_d)  -------generally
print("{}/{}".format(result_n,result_d))        #

Enter first term numerator: 2
Enter first term denominator: 3
Enter second term numerator: 6
Enter second term denominator: 2
22/6

### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.

**hint**---milk tank is like a cube, glasses are like cylinder
====milk tank volume/1glass milk---can solve our problem


Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm

In [ ]:
# Write your code here
l_tank=float(input("Enter the length of the tank: "))
b_tank=float(input("Enter the breadth of the tank: "))
h_tank=float(input("Enter the height of the tank: "))

r_glass=float(input("Enter the radius of the glass: "))
h_glass=float(input("Enter the height of the glass: "))

vol_tank=l_tank*b_tank*h_tank                      # vol of a cube=lbh
vol_glass=3.14*r_glass*r_glass*h_glass             # vol of a cylinder=pie*r2*h

print("no. of glasses are: ",vol_tank/vol_glass)

#below we again writing the code but by use math.floor module fn to approximate the decimals to a complete no.

Enter the length of the tank: 10
Enter the breadth of the tank: 19
Enter the height of the tank: 10
Enter the radius of the glass: 2
Enter the height of the glass: 5
no. of glasses are:  30.254777070063692

In [ ]:
# Write your code here
import math          # just to use floor funtion in the print

l_tank=float(input("Enter the length of the tank: "))
b_tank=float(input("Enter the breadth of the tank: "))
h_tank=float(input("Enter the height of the tank: "))

r_glass=float(input("Enter the radius of the glass: "))
h_glass=float(input("Enter the height of the glass: "))

vol_tank=l_tank*b_tank*h_tank                      # vol of a cube=lbh
vol_glass=3.14*r_glass*r_glass*h_glass             # vol of a cylinder=pie*r2*h

print("no. of glasses are: ",math.floor(vol_tank/vol_glass))        #math.floor use to approximate the decimals to a complete no.

Enter the length of the tank: 10
Enter the breadth of the tank: 19
Enter the height of the tank: 10
Enter the radius of the glass: 2
Enter the height of the glass: 5
no. of glasses are:  30